# Generated by Django 6.0.6 on 2026-07-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('comicvine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVineVolumeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('start_year', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source_issue_count', models.PositiveIntegerField(blank=True, null=True)),
                ('first_issue_date', models.DateField(blank=True, null=True)),
                ('last_issue_date', models.DateField(blank=True, null=True)),
                ('first_issue_number', models.CharField(blank=True, max_length=50)),
                ('last_issue_number', models.CharField(blank=True, max_length=50)),
                ('suggested_kind', models.CharField(choices=[('unknown', 'Unknown'), ('run', 'Run'), ('collected_volume', 'Collected volume'), ('ignore', 'Ignore')], default='unknown', max_length=30)),
                ('reviewed_kind', models.CharField(choices=[('unknown', 'Unknown'), ('run', 'Run'), ('collected_volume', 'Collected volume'), ('ignore', 'Ignore')], default='unknown', max_length=30)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('ignored', 'Ignored')], db_index=True, default='needs_review', max_length=30)),
                ('review_reason', models.CharField(blank=True, max_length=500)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comicvine_volume_candidates', to='catalog.comicrun')),
                ('catalog_volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comicvine_volume_candidates', to='catalog.comicvolume')),
                ('comicvine_volume', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_candidate', to='comicvine.comicvinevolume')),
            ],
            options={
                'ordering': ['publisher_name', 'title', 'start_year', 'comicvine_volume__comicvine_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('catalog_run__isnull', False)), fields=('catalog_run',), name='unique_candidate_catalog_run'), models.UniqueConstraint(condition=models.Q(('catalog_volume__isnull', False)), fields=('catalog_volume',), name='unique_candidate_catalog_volume')],
            },
        ),
    ]
