# Generated by Django 6.0.6 on 2026-07-10 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_comicvolume_title'),
        ('comicvine', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicvinevolumecandidate',
            options={'ordering': ['publisher_name', 'normalized_title', 'title', 'start_year', 'comicvine_volume__comicvine_id']},
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='analysis_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='analysis_status',
            field=models.CharField(choices=[('not_analyzed', 'Not analyzed'), ('confirmed_run', 'Confirmed run'), ('confirmed_collected_volume', 'Confirmed collected volume'), ('unresolved', 'Unresolved'), ('conflict', 'Conflict'), ('insufficient_data', 'Insufficient data')], db_index=True, default='not_analyzed', max_length=40),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='analysis_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='catalog_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='catalog_status',
            field=models.CharField(choices=[('not_ready', 'Not ready'), ('ready_to_apply', 'Ready to apply'), ('applied', 'Applied'), ('update_available', 'Update available'), ('blocked', 'Blocked')], db_index=True, default='not_ready', max_length=40),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='determination_source',
            field=models.CharField(choices=[('not_determined', 'Not determined'), ('algorithm', 'Algorithm'), ('manual', 'Manual')], db_index=True, default='not_determined', max_length=40),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='proposed_parent_run_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_collected_volume_candidates', to='ingestion.comicvinevolumecandidate'),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='source_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='source_date_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('store_date', 'Store date'), ('cover_date', 'Cover date')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='source_issue_fingerprint',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='source_volume_date_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comicvinevolumecandidate',
            name='review_status',
            field=models.CharField(choices=[('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='needs_review', max_length=30),
        ),
        migrations.AlterField(
            model_name='comicvinevolumecandidate',
            name='reviewed_kind',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('run', 'Run'), ('collected_volume', 'Collected volume')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='comicvinevolumecandidate',
            name='suggested_kind',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('run', 'Run'), ('collected_volume', 'Collected volume')], default='unknown', max_length=30),
        ),
        migrations.CreateModel(
            name='MarvelCatalogRunSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_volume_date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('source_issue_fingerprint', models.CharField(blank=True, max_length=128)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('source_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_run_source_link', to='ingestion.comicvinevolumecandidate')),
                ('catalog_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvel_source_links', to='catalog.comicrun')),
                ('comicvine_volume', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marvel_catalog_run_source', to='comicvine.comicvinevolume')),
            ],
            options={
                'ordering': ['catalog_run', 'comicvine_volume'],
            },
        ),
        migrations.CreateModel(
            name='MarvelCatalogIssueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_issue_date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('source_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marvel_source_link', to='catalog.comicissue')),
                ('catalog_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvel_issue_source_links', to='catalog.comicrun')),
                ('comicvine_issue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marvel_catalog_issue_source', to='comicvine.comicvineissue')),
                ('comicvine_volume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marvel_catalog_issue_sources', to='comicvine.comicvinevolume')),
                ('run_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_source_links', to='ingestion.marvelcatalogrunsource')),
            ],
            options={
                'ordering': ['catalog_run', 'catalog_issue', 'comicvine_issue'],
            },
        ),
        migrations.CreateModel(
            name='MarvelIngestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(db_index=True, default='Marvel', max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('display_title', models.CharField(blank=True, max_length=500)),
                ('source_volume_count', models.PositiveIntegerField(default=0)),
                ('source_issue_count', models.PositiveIntegerField(default=0)),
                ('first_issue_date', models.DateField(blank=True, null=True)),
                ('last_issue_date', models.DateField(blank=True, null=True)),
                ('source_volume_fingerprint', models.CharField(blank=True, max_length=128)),
                ('source_issue_fingerprint', models.CharField(blank=True, max_length=128)),
                ('analysis_version', models.PositiveIntegerField(default=1)),
                ('analysis_status', models.CharField(choices=[('not_analyzed', 'Not analyzed'), ('confirmed_by_rule', 'Confirmed by rule'), ('unresolved', 'Unresolved'), ('conflict', 'Conflict'), ('insufficient_data', 'Insufficient data')], db_index=True, default='not_analyzed', max_length=40)),
                ('catalog_status', models.CharField(choices=[('not_ready', 'Not ready'), ('ready_to_apply', 'Ready to apply'), ('applied', 'Applied'), ('update_available', 'Update available'), ('blocked', 'Blocked')], db_index=True, default='not_ready', max_length=40)),
                ('determination_source', models.CharField(choices=[('not_determined', 'Not determined'), ('algorithm', 'Algorithm'), ('manual', 'Manual')], db_index=True, default='not_determined', max_length=40)),
                ('analysis_reason', models.CharField(blank=True, max_length=500)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('source_changed_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marvel_ingestion_groups', to='catalog.comicrun')),
            ],
            options={
                'ordering': ['publisher_name', 'normalized_title', 'first_issue_date', 'last_issue_date'],
            },
        ),
        migrations.AddField(
            model_name='comicvinevolumecandidate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volume_candidates', to='ingestion.marvelingestiongroup'),
        ),
        migrations.CreateModel(
            name='MarvelVolumeContainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('store_date', 'Store date'), ('cover_date', 'Cover date')], max_length=30)),
                ('run_first_issue_date', models.DateField()),
                ('run_last_issue_date', models.DateField()),
                ('collected_first_issue_date', models.DateField()),
                ('collected_last_issue_date', models.DateField()),
                ('analysis_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed_by_rule', 'Confirmed by rule'), ('unresolved', 'Unresolved'), ('conflict', 'Conflict'), ('invalidated_by_source_change', 'Invalidated by source change')], db_index=True, default='confirmed_by_rule', max_length=40)),
                ('determination_source', models.CharField(choices=[('algorithm', 'Algorithm'), ('manual', 'Manual')], db_index=True, default='algorithm', max_length=40)),
                ('determination_reason', models.CharField(blank=True, max_length=500)),
                ('run_source_issue_fingerprint', models.CharField(blank=True, max_length=128)),
                ('collected_source_issue_fingerprint', models.CharField(blank=True, max_length=128)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('source_changed_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_volume_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_by_relationships', to='ingestion.comicvinevolumecandidate')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containment_relationships', to='ingestion.marvelingestiongroup')),
                ('run_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_volume_relationships', to='ingestion.comicvinevolumecandidate')),
            ],
            options={
                'ordering': ['group', 'run_candidate', 'collected_first_issue_date', 'collected_last_issue_date', 'collected_volume_candidate'],
            },
        ),
        migrations.CreateModel(
            name='MarvelCatalogVolumeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_volume_date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('source_issue_fingerprint', models.CharField(blank=True, max_length=128)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('source_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_volume_source_link', to='ingestion.comicvinevolumecandidate')),
                ('catalog_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvel_collected_volume_source_links', to='catalog.comicrun')),
                ('catalog_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvel_source_links', to='catalog.comicvolume')),
                ('comicvine_volume', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marvel_catalog_volume_source', to='comicvine.comicvinevolume')),
                ('containment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_volume_source_links', to='ingestion.marvelvolumecontainment')),
            ],
            options={
                'ordering': ['catalog_run', 'catalog_volume', 'comicvine_volume'],
            },
        ),
        migrations.AddConstraint(
            model_name='marvelingestiongroup',
            constraint=models.UniqueConstraint(fields=('publisher_name', 'normalized_title'), name='unique_marvel_ingestion_group_title'),
        ),
        migrations.AddConstraint(
            model_name='marvelvolumecontainment',
            constraint=models.UniqueConstraint(fields=('run_candidate', 'collected_volume_candidate'), name='unique_marvel_volume_containment_pair'),
        ),
    ]
