# Generated by Django 6.0.6 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_comicvolume_title"),
        ("comicvine", "0001_initial"),
        ("ingestion", "0002_alter_comicvinevolumecandidate_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="MarvelCatalogVolumeSource"),
        migrations.DeleteModel(name="MarvelCatalogIssueSource"),
        migrations.DeleteModel(name="MarvelCatalogRunSource"),
        migrations.DeleteModel(name="MarvelVolumeContainment"),
        migrations.DeleteModel(name="ComicVineVolumeCandidate"),
        migrations.DeleteModel(name="MarvelIngestionGroup"),
        migrations.CreateModel(
            name="ComicVineVolumeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publisher_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                (
                    "normalized_title",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                (
                    "start_year",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "source_issue_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source_date_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("store_date", "Store date"),
                            ("cover_date", "Cover date"),
                            ("best_available", "Best available date"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("first_issue_date", models.DateField(blank=True, null=True)),
                ("last_issue_date", models.DateField(blank=True, null=True)),
                (
                    "first_issue_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "last_issue_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "source_volume_date_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("source_fingerprint", models.CharField(blank=True, max_length=128)),
                ("analysis_version", models.PositiveIntegerField(default=3)),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("not_analyzed", "Not analyzed"),
                            ("confirmed_run", "Confirmed run"),
                            ("collection_container", "Collection container"),
                            ("unresolved", "Unresolved"),
                            ("conflict", "Conflict"),
                            ("insufficient_data", "Insufficient data"),
                        ],
                        db_index=True,
                        default="not_analyzed",
                        max_length=40,
                    ),
                ),
                (
                    "catalog_status",
                    models.CharField(
                        choices=[
                            ("not_ready", "Not ready"),
                            ("ready_to_apply", "Ready to apply"),
                            ("applied", "Applied"),
                            ("update_available", "Update available"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="not_ready",
                        max_length=40,
                    ),
                ),
                (
                    "determination_source",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("algorithm", "Algorithm"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="not_determined",
                        max_length=40,
                    ),
                ),
                ("analysis_reason", models.CharField(blank=True, max_length=500)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("needs_review", "Needs review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="needs_review",
                        max_length=30,
                    ),
                ),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("source_changed_at", models.DateTimeField(blank=True, null=True)),
                ("catalog_applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comicvine_volume_candidates",
                        to="catalog.comicrun",
                    ),
                ),
                (
                    "comicvine_volume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_candidate",
                        to="comicvine.comicvinevolume",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "publisher_name",
                    "normalized_title",
                    "start_year",
                    "comicvine_volume__comicvine_id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("catalog_run__isnull", False)),
                        fields=("catalog_run",),
                        name="unique_candidate_catalog_run",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComicVineCollectedEditionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publisher_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("source_title", models.CharField(blank=True, max_length=500)),
                ("volume_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("collecting_text", models.TextField(blank=True)),
                ("unresolved_reference_text", models.TextField(blank=True)),
                ("source_reference_count", models.PositiveIntegerField(default=0)),
                ("source_issue_count", models.PositiveIntegerField(default=0)),
                (
                    "primary_first_issue_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "primary_last_issue_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "source_issue_date_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("source_fingerprint", models.CharField(blank=True, max_length=128)),
                ("analysis_version", models.PositiveIntegerField(default=3)),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("not_analyzed", "Not analyzed"),
                            (
                                "confirmed_collected_volume",
                                "Confirmed collected volume",
                            ),
                            ("unresolved", "Unresolved"),
                            ("conflict", "Conflict"),
                            ("insufficient_data", "Insufficient data"),
                        ],
                        db_index=True,
                        default="not_analyzed",
                        max_length=40,
                    ),
                ),
                (
                    "catalog_status",
                    models.CharField(
                        choices=[
                            ("not_ready", "Not ready"),
                            ("ready_to_apply", "Ready to apply"),
                            ("applied", "Applied"),
                            ("update_available", "Update available"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="not_ready",
                        max_length=40,
                    ),
                ),
                (
                    "determination_source",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("algorithm", "Algorithm"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="not_determined",
                        max_length=40,
                    ),
                ),
                ("analysis_reason", models.CharField(blank=True, max_length=500)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("needs_review", "Needs review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="needs_review",
                        max_length=30,
                    ),
                ),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("source_changed_at", models.DateTimeField(blank=True, null=True)),
                ("catalog_applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comicvine_collected_edition_candidates",
                        to="catalog.comicvolume",
                    ),
                ),
                (
                    "comicvine_issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collected_edition_candidate",
                        to="comicvine.comicvineissue",
                    ),
                ),
                (
                    "proposed_parent_run_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_collected_editions",
                        to="ingestion.comicvinevolumecandidate",
                    ),
                ),
                (
                    "source_collection_volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collected_edition_candidates",
                        to="comicvine.comicvinevolume",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "publisher_name",
                    "source_collection_volume__name",
                    "release_date",
                    "volume_number",
                    "comicvine_issue__comicvine_id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("catalog_volume__isnull", False)),
                        fields=("catalog_volume",),
                        name="unique_collected_candidate_catalog_volume",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComicVineCollectedEditionIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_order", models.PositiveIntegerField()),
                ("primary_run", models.BooleanField(default=False)),
                ("reference_text", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_issue_links",
                        to="ingestion.comicvinecollectededitioncandidate",
                    ),
                ),
                (
                    "source_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collected_edition_memberships",
                        to="comicvine.comicvineissue",
                    ),
                ),
                (
                    "source_run_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collected_edition_issue_links",
                        to="ingestion.comicvinevolumecandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["candidate", "issue_order", "source_issue"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "source_issue"),
                        name="unique_collected_candidate_source_issue",
                    ),
                    models.UniqueConstraint(
                        fields=("candidate", "issue_order"),
                        name="unique_collected_candidate_issue_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarvelCatalogRunSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_volume_date_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("source_fingerprint", models.CharField(blank=True, max_length=128)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
                ("source_changed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_run_source_link",
                        to="ingestion.comicvinevolumecandidate",
                    ),
                ),
                (
                    "catalog_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvel_source_links",
                        to="catalog.comicrun",
                    ),
                ),
                (
                    "comicvine_volume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marvel_catalog_run_source",
                        to="comicvine.comicvinevolume",
                    ),
                ),
            ],
            options={"ordering": ["catalog_run", "comicvine_volume"]},
        ),
        migrations.CreateModel(
            name="MarvelCatalogIssueSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_issue_date_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
                ("source_changed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvel_source_link",
                        to="catalog.comicissue",
                    ),
                ),
                (
                    "catalog_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvel_issue_source_links",
                        to="catalog.comicrun",
                    ),
                ),
                (
                    "comicvine_issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marvel_catalog_issue_source",
                        to="comicvine.comicvineissue",
                    ),
                ),
                (
                    "comicvine_volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marvel_catalog_issue_sources",
                        to="comicvine.comicvinevolume",
                    ),
                ),
                (
                    "run_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_source_links",
                        to="ingestion.marvelcatalogrunsource",
                    ),
                ),
            ],
            options={
                "ordering": ["catalog_run", "catalog_issue", "comicvine_issue"]
            },
        ),
        migrations.CreateModel(
            name="MarvelCatalogVolumeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_issue_date_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("source_fingerprint", models.CharField(blank=True, max_length=128)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
                ("source_changed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_volume_source_link",
                        to="ingestion.comicvinecollectededitioncandidate",
                    ),
                ),
                (
                    "catalog_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvel_collected_volume_source_links",
                        to="catalog.comicrun",
                    ),
                ),
                (
                    "catalog_volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvel_source_links",
                        to="catalog.comicvolume",
                    ),
                ),
                (
                    "comicvine_issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marvel_catalog_volume_source",
                        to="comicvine.comicvineissue",
                    ),
                ),
            ],
            options={
                "ordering": ["catalog_run", "catalog_volume", "comicvine_issue"]
            },
        ),
    ]