# Generated by Django 6.0.6 on 2026-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=200)),
                ('issue_number', models.CharField(max_length=20)),
                ('issue_title', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
