# Generated by Django 6.0.6 on 2026-06-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicissue',
            old_name='release_date',
            new_name='cover_date',
        ),
        migrations.RemoveField(
            model_name='comicissue',
            name='series_title',
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='store_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='volume_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='issue_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='issue_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
