# Generated by Django 6.0.6 on 2026-06-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_rename_release_date_comicissue_cover_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('comicvine_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comicissue',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='comicissue',
            name='volume_name',
        ),
        migrations.AddField(
            model_name='comicissue',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='comics.comicvolume'),
        ),
    ]
