# Generated by Django 6.0.6 on 2026-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comicvolume_remove_comicissue_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVineImportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('backfill_before_date', models.DateField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
