# Generated by Django 6.0.6 on 2026-06-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_comicvineimportstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicvineimportstate',
            name='backfill_offset',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
