# Generated by Django 6.0.6 on 2026-06-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_comicvineimportstate_backfill_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVineDateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(unique=True)),
                ('next_offset', models.PositiveIntegerField(default=0)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.DeleteModel(
            name='ComicVineImportState',
        ),
    ]
