# Generated by Django 6.0.6 on 2026-06-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_comicvinedatescan_delete_comicvineimportstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVineSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('update_tracking_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comicvinedatescan',
            options={'ordering': ['scan_kind', '-scan_date']},
        ),
        migrations.AddField(
            model_name='comicissue',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='date_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvinedatescan',
            name='scan_kind',
            field=models.CharField(choices=[('issue_date_added', 'Issue date added'), ('issue_date_last_updated', 'Issue date last updated'), ('volume_date_last_updated', 'Volume date last updated')], default='issue_date_added', max_length=50),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='date_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comicvinedatescan',
            name='scan_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='comicvinedatescan',
            constraint=models.UniqueConstraint(fields=('scan_kind', 'scan_date'), name='unique_comicvine_scan_kind_date'),
        ),
    ]
