# Generated by Django 6.0.6 on 2026-06-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_comicvinesyncstate_alter_comicvinedatescan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicCreditRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComicPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='comicissue',
            name='image_url',
        ),
        migrations.AddField(
            model_name='comicissue',
            name='aliases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='api_detail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_medium_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_original_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_screen_large_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_screen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_small_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_super_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_thumb_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='comicvine_image_tiny_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='deck',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='has_staff_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='aliases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='api_detail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_medium_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_original_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_screen_large_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_screen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_small_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_super_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_thumb_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='comicvine_image_tiny_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='count_of_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='deck',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='display_image_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('first_issue', 'First issue'), ('comicvine_volume', 'Comic Vine volume'), ('manual', 'Manual')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='display_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='first_issue_api_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='first_issue_comicvine_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='first_issue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='first_issue_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='last_issue_api_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='last_issue_comicvine_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='last_issue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='last_issue_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='latest_local_issue_store_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='manual_final_issue_store_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='manual_status_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='publisher_api_detail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='publisher_comicvine_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='run_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('likely_ongoing', 'Likely ongoing'), ('likely_ended', 'Likely ended'), ('manual_ongoing', 'Manual ongoing'), ('manual_ended', 'Manual ended')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='run_status_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='run_status_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('date_window', 'Date window'), ('manual', 'Manual')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='start_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='comicvine_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicvolume',
            name='comicvine_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ComicIssuePersonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_credits', to='comics.comicissue')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_credits', to='comics.comiccreditrole')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_credits', to='comics.comicperson')),
            ],
            options={
                'ordering': ['issue', 'role', 'person'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'person', 'role'), name='unique_issue_person_role_credit')],
            },
        ),
        migrations.CreateModel(
            name='ComicVolumePersonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_count', models.PositiveIntegerField(blank=True, null=True)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_credits', to='comics.comicperson')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_credits', to='comics.comicvolume')),
            ],
            options={
                'ordering': ['volume', 'person'],
                'constraints': [models.UniqueConstraint(fields=('volume', 'person'), name='unique_volume_person_credit')],
            },
        ),
    ]
