# Generated by Django 6.0.6 on 2026-06-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_comiccreditrole_comicperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicissue',
            name='detail_hydrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='detail_hydration_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='detail_hydrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comicvolume',
            name='detail_hydration_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
