# Generated by Django 6.0.6 on 2026-06-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_comicissue_detail_hydrated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicStoryArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicIssueAssociatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('medium_url', models.URLField(blank=True, max_length=500)),
                ('screen_url', models.URLField(blank=True, max_length=500)),
                ('screen_large_url', models.URLField(blank=True, max_length=500)),
                ('small_url', models.URLField(blank=True, max_length=500)),
                ('super_url', models.URLField(blank=True, max_length=500)),
                ('thumb_url', models.URLField(blank=True, max_length=500)),
                ('tiny_url', models.URLField(blank=True, max_length=500)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('image_tags', models.CharField(blank=True, max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_images', to='comics.comicissue')),
            ],
            options={
                'ordering': ['issue', 'position'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'position'), name='unique_issue_associated_image_position')],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueCharacterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comics.comiccharacter')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='comics.comicissue')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'character'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'character', 'relation_type'), name='unique_issue_character_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comics.comicconcept')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='comics.comicissue')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'concept'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'concept', 'relation_type'), name='unique_issue_concept_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueLocationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='comics.comicissue')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comics.comiclocation')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'location'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'location', 'relation_type'), name='unique_issue_location_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='comics.comicissue')),
                ('comic_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comics.comicobject')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'comic_object'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'comic_object', 'relation_type'), name='unique_issue_object_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueStoryArcLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_arc_links', to='comics.comicissue')),
                ('story_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comics.comicstoryarc')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'story_arc'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'story_arc', 'relation_type'), name='unique_issue_story_arc_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueTeamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='comics.comicissue')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comics.comicteam')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'team'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'team', 'relation_type'), name='unique_issue_team_relation')],
            },
        ),
    ]
