# Generated by Django 6.0.6 on 2026-06-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_comiccharacter_comicconcept_comiclocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comiccharacter',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicconcept',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='comicvine_image_tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='issue_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicissueassociatedimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicissueassociatedimage',
            name='image_tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comiclocation',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicobject',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicperson',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicstoryarc',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicteam',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicvolume',
            name='comicvine_image_tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicvolume',
            name='first_issue_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicvolume',
            name='last_issue_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comicvolume',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comicvolume',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
