# Generated by Django 6.0.6 on 2026-06-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_alter_comiccharacter_name_alter_comicconcept_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicvolume',
            name='list_data_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
