# Generated by Django 6.0.6 on 2026-06-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0012_comicvolume_list_data_refreshed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicvinedatescan',
            name='scan_kind',
            field=models.CharField(choices=[('issue_date_added', 'Issue date added'), ('issue_date_last_updated', 'Issue date last updated'), ('volume_date_added', 'Volume date added'), ('volume_date_last_updated', 'Volume date last updated')], default='issue_date_added', max_length=50),
        ),
    ]
