# Generated by Django 6.0.6 on 2026-07-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVineCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicVineConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicVineCreditRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComicVineLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicVineObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicVinePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComicVineStoryArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicVineSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('update_tracking_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicVineTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicVineVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publisher_comicvine_id', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher_api_detail_url', models.URLField(blank=True, max_length=500)),
                ('start_year', models.CharField(blank=True, max_length=20)),
                ('count_of_issues', models.PositiveIntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('aliases', models.TextField(blank=True)),
                ('deck', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('comicvine_image_icon_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_medium_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_screen_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_screen_large_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_small_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_super_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_thumb_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_tiny_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_original_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_tags', models.CharField(blank=True, max_length=500)),
                ('display_image_url', models.URLField(blank=True, max_length=500)),
                ('display_image_source', models.CharField(choices=[('unknown', 'Unknown'), ('first_issue', 'First issue'), ('comicvine_volume', 'Comic Vine volume'), ('manual', 'Manual')], default='unknown', max_length=30)),
                ('first_issue_comicvine_id', models.PositiveIntegerField(blank=True, null=True)),
                ('first_issue_number', models.CharField(blank=True, max_length=50)),
                ('first_issue_name', models.CharField(blank=True, max_length=500)),
                ('first_issue_api_url', models.URLField(blank=True, max_length=500)),
                ('last_issue_comicvine_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_issue_number', models.CharField(blank=True, max_length=50)),
                ('last_issue_name', models.CharField(blank=True, max_length=500)),
                ('last_issue_api_url', models.URLField(blank=True, max_length=500)),
                ('list_data_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('detail_hydration_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('detail_hydrated_at', models.DateTimeField(blank=True, null=True)),
                ('latest_local_issue_store_date', models.DateField(blank=True, null=True)),
                ('run_status', models.CharField(choices=[('unknown', 'Unknown'), ('likely_ongoing', 'Likely ongoing'), ('likely_ended', 'Likely ended'), ('manual_ongoing', 'Manual ongoing'), ('manual_ended', 'Manual ended')], default='unknown', max_length=30)),
                ('run_status_source', models.CharField(choices=[('unknown', 'Unknown'), ('date_window', 'Date window'), ('manual', 'Manual')], default='unknown', max_length=30)),
                ('run_status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('manual_final_issue_store_date', models.DateField(blank=True, null=True)),
                ('manual_status_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicVineDateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_kind', models.CharField(choices=[('issue_date_added', 'Issue date added'), ('issue_date_last_updated', 'Issue date last updated'), ('volume_date_added', 'Volume date added'), ('volume_date_last_updated', 'Volume date last updated')], default='issue_date_added', max_length=50)),
                ('scan_date', models.DateField()),
                ('next_offset', models.PositiveIntegerField(default=0)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scan_kind', '-scan_date'],
                'constraints': [models.UniqueConstraint(fields=('scan_kind', 'scan_date'), name='unique_comicvine_scan_kind_date')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('issue_number', models.CharField(max_length=50)),
                ('issue_title', models.CharField(blank=True, max_length=500)),
                ('cover_date', models.DateField(blank=True, null=True)),
                ('store_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('aliases', models.TextField(blank=True)),
                ('deck', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('has_staff_review', models.BooleanField(default=False)),
                ('detail_hydration_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('detail_hydrated_at', models.DateTimeField(blank=True, null=True)),
                ('comicvine_image_icon_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_medium_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_screen_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_screen_large_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_small_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_super_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_thumb_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_tiny_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_original_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_image_tags', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='comicvine.comicvinevolume')),
            ],
        ),
        migrations.CreateModel(
            name='ComicVineIssueAssociatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('medium_url', models.URLField(blank=True, max_length=500)),
                ('screen_url', models.URLField(blank=True, max_length=500)),
                ('screen_large_url', models.URLField(blank=True, max_length=500)),
                ('small_url', models.URLField(blank=True, max_length=500)),
                ('super_url', models.URLField(blank=True, max_length=500)),
                ('thumb_url', models.URLField(blank=True, max_length=500)),
                ('tiny_url', models.URLField(blank=True, max_length=500)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('image_tags', models.CharField(blank=True, max_length=500)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_images', to='comicvine.comicvineissue')),
            ],
            options={
                'ordering': ['issue', 'position'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'position'), name='unique_comicvine_issue_associated_image_position')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssueCharacterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comicvine.comicvinecharacter')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='comicvine.comicvineissue')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'character'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'character', 'relation_type'), name='unique_comicvine_issue_character_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssueConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comicvine.comicvineconcept')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='comicvine.comicvineissue')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'concept'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'concept', 'relation_type'), name='unique_comicvine_issue_concept_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssueLocationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='comicvine.comicvineissue')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comicvine.comicvinelocation')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'location'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'location', 'relation_type'), name='unique_comicvine_issue_location_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssueObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='comicvine.comicvineissue')),
                ('comic_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comicvine.comicvineobject')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'comic_object'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'comic_object', 'relation_type'), name='unique_comicvine_issue_object_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssuePersonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_credits', to='comicvine.comicvineissue')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_credits', to='comicvine.comicvinecreditrole')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_credits', to='comicvine.comicvineperson')),
            ],
            options={
                'ordering': ['issue', 'role', 'person'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'person', 'role'), name='unique_comicvine_issue_person_role_credit')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssueStoryArcLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_arc_links', to='comicvine.comicvineissue')),
                ('story_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comicvine.comicvinestoryarc')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'story_arc'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'story_arc', 'relation_type'), name='unique_comicvine_issue_story_arc_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineIssueTeamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('credit', 'Credit'), ('first_appearance', 'First appearance'), ('died_in', 'Died in'), ('disbanded_in', 'Disbanded in')], default='credit', max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='comicvine.comicvineissue')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='comicvine.comicvineteam')),
            ],
            options={
                'ordering': ['issue', 'relation_type', 'team'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'team', 'relation_type'), name='unique_comicvine_issue_team_relation')],
            },
        ),
        migrations.CreateModel(
            name='ComicVineVolumePersonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_count', models.PositiveIntegerField(blank=True, null=True)),
                ('api_detail_url', models.URLField(blank=True, max_length=500)),
                ('comicvine_url', models.URLField(blank=True, max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_credits', to='comicvine.comicvineperson')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_credits', to='comicvine.comicvinevolume')),
            ],
            options={
                'ordering': ['volume', 'person'],
                'constraints': [models.UniqueConstraint(fields=('volume', 'person'), name='unique_comicvine_volume_person_credit')],
            },
        ),
    ]
