# Generated by Django 6.0.6 on 2026-07-09 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_comicvolume_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='catalog.comicrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['user', '-followed_at'], name='reading_fr_user_followed_idx'), models.Index(fields=['run'], name='reading_fr_run_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'run'), name='unique_followed_run_per_user')],
            },
        ),
        migrations.CreateModel(
            name='IssueProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned to read'), ('reading', 'Reading'), ('read', 'Read')], default='planned', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='catalog.comicissue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['issue__run__publisher__name', 'issue__run__title', 'issue__store_date', 'issue__issue_number'],
                'indexes': [models.Index(fields=['user', 'status'], name='reading_ip_user_status_idx'), models.Index(fields=['issue'], name='reading_ip_issue_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'issue'), name='unique_user_issue_progress')],
            },
        ),
        migrations.CreateModel(
            name='VolumeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned to read'), ('reading', 'Reading'), ('read', 'Read')], default='planned', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_progress', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='catalog.comicvolume')),
            ],
            options={
                'ordering': ['volume__publisher__name', 'volume__run__title', 'volume__volume_number', 'volume__release_date', 'volume__title'],
                'indexes': [models.Index(fields=['user', 'status'], name='reading_vp_user_status_idx'), models.Index(fields=['volume'], name='reading_vp_volume_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'volume'), name='unique_user_volume_progress')],
            },
        ),
    ]
