# Generated by Django 6.0.6 on 2026-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueprogress',
            options={'ordering': ['issue__run__publisher__name', 'issue__run__title', 'issue__published_date', 'issue__issue_number']},
        ),
    ]
