# Generated by Django 6.0.6 on 2026-07-12 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_store_date_to_published_date'),
        ('reading', '0002_rename_store_date_to_published_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followedrun',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned to read'), ('reading', 'Reading'), ('read', 'Read')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='followedrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='followedrun',
            index=models.Index(fields=['user', 'status'], name='reading_fr_user_status_idx'),
        ),
    ]
