# Generated by Django 6.0.6 on 2026-07-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_comiconeshotcredit"),
        ("reading", "0003_followedrun_status_followedrun_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneShotProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned to read"),
                            ("reading", "Reading"),
                            ("read", "Read"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "one_shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="catalog.comiconeshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_shot_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "one_shot__publisher__name",
                    "one_shot__published_date",
                    "one_shot__title",
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="reading_osp_user_status_idx"
                    ),
                    models.Index(fields=["one_shot"], name="reading_osp_one_shot_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "one_shot"),
                        name="unique_user_one_shot_progress",
                    )
                ],
            },
        ),
    ]
