# Generated by Django 6.0.6 on 2026-07-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('show_by_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComicRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_icon_url', models.URLField(blank=True, max_length=500)),
                ('image_medium_url', models.URLField(blank=True, max_length=500)),
                ('image_screen_url', models.URLField(blank=True, max_length=500)),
                ('image_screen_large_url', models.URLField(blank=True, max_length=500)),
                ('image_small_url', models.URLField(blank=True, max_length=500)),
                ('image_super_url', models.URLField(blank=True, max_length=500)),
                ('image_thumb_url', models.URLField(blank=True, max_length=500)),
                ('image_tiny_url', models.URLField(blank=True, max_length=500)),
                ('image_original_url', models.URLField(blank=True, max_length=500)),
                ('image_tags', models.CharField(blank=True, max_length=500)),
                ('display_image_url', models.URLField(blank=True, max_length=500)),
                ('display_image_source', models.CharField(choices=[('unknown', 'Unknown'), ('source_data', 'Source data'), ('manual', 'Manual')], default='unknown', max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('start_year', models.CharField(blank=True, max_length=20)),
                ('first_issue_date', models.DateField(blank=True, null=True)),
                ('last_issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('ongoing', 'Ongoing'), ('ended', 'Ended')], default='unknown', max_length=20)),
                ('issue_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='catalog.comicpublisher')),
            ],
            options={
                'ordering': ['publisher__name', 'title', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='ComicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_icon_url', models.URLField(blank=True, max_length=500)),
                ('image_medium_url', models.URLField(blank=True, max_length=500)),
                ('image_screen_url', models.URLField(blank=True, max_length=500)),
                ('image_screen_large_url', models.URLField(blank=True, max_length=500)),
                ('image_small_url', models.URLField(blank=True, max_length=500)),
                ('image_super_url', models.URLField(blank=True, max_length=500)),
                ('image_thumb_url', models.URLField(blank=True, max_length=500)),
                ('image_tiny_url', models.URLField(blank=True, max_length=500)),
                ('image_original_url', models.URLField(blank=True, max_length=500)),
                ('image_tags', models.CharField(blank=True, max_length=500)),
                ('display_image_url', models.URLField(blank=True, max_length=500)),
                ('display_image_source', models.CharField(choices=[('unknown', 'Unknown'), ('source_data', 'Source data'), ('manual', 'Manual')], default='unknown', max_length=30)),
                ('issue_number', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('cover_date', models.DateField(blank=True, null=True)),
                ('store_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='catalog.comicrun')),
            ],
            options={
                'ordering': ['run', 'store_date', 'issue_number'],
            },
        ),
        migrations.CreateModel(
            name='ComicVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_icon_url', models.URLField(blank=True, max_length=500)),
                ('image_medium_url', models.URLField(blank=True, max_length=500)),
                ('image_screen_url', models.URLField(blank=True, max_length=500)),
                ('image_screen_large_url', models.URLField(blank=True, max_length=500)),
                ('image_small_url', models.URLField(blank=True, max_length=500)),
                ('image_super_url', models.URLField(blank=True, max_length=500)),
                ('image_thumb_url', models.URLField(blank=True, max_length=500)),
                ('image_tiny_url', models.URLField(blank=True, max_length=500)),
                ('image_original_url', models.URLField(blank=True, max_length=500)),
                ('image_tags', models.CharField(blank=True, max_length=500)),
                ('display_image_url', models.URLField(blank=True, max_length=500)),
                ('display_image_source', models.CharField(choices=[('unknown', 'Unknown'), ('source_data', 'Source data'), ('manual', 'Manual')], default='unknown', max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('volume_number', models.CharField(blank=True, max_length=50)),
                ('first_issue_number', models.CharField(blank=True, max_length=50)),
                ('last_issue_number', models.CharField(blank=True, max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('issue_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volumes', to='catalog.comicpublisher')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='catalog.comicrun')),
            ],
            options={
                'ordering': ['publisher__name', 'run', 'volume_number', 'release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ComicVolumeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_order', models.PositiveIntegerField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_in', to='catalog.comicissue')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_issues', to='catalog.comicvolume')),
            ],
            options={
                'ordering': ['volume', 'issue_order', 'issue__store_date', 'issue__issue_number'],
            },
        ),
        migrations.CreateModel(
            name='ComicVolumeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_order', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.comicvolume')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_credits', to='catalog.creditperson')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volume_credits', to='catalog.creditrole')),
            ],
            options={
                'ordering': ['volume', 'role__display_order', 'credit_order', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='ComicRunCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_order', models.PositiveIntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.comicrun')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_credits', to='catalog.creditperson')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_credits', to='catalog.creditrole')),
            ],
            options={
                'ordering': ['run', 'role__display_order', 'credit_order', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='ComicIssueCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_order', models.PositiveIntegerField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.comicissue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_credits', to='catalog.creditperson')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_credits', to='catalog.creditrole')),
            ],
            options={
                'ordering': ['issue', 'role__display_order', 'credit_order', 'person__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='comicissue',
            constraint=models.UniqueConstraint(fields=('run', 'issue_number'), name='unique_comic_issue_number_per_run'),
        ),
        migrations.AddConstraint(
            model_name='comicvolumeissue',
            constraint=models.UniqueConstraint(fields=('volume', 'issue'), name='unique_comic_volume_issue'),
        ),
        migrations.AddConstraint(
            model_name='comicvolumecredit',
            constraint=models.UniqueConstraint(fields=('volume', 'person', 'role'), name='unique_comic_volume_person_role_credit'),
        ),
        migrations.AddConstraint(
            model_name='comicruncredit',
            constraint=models.UniqueConstraint(fields=('run', 'person', 'role'), name='unique_comic_run_person_role_credit'),
        ),
        migrations.AddConstraint(
            model_name='comicissuecredit',
            constraint=models.UniqueConstraint(fields=('issue', 'person', 'role'), name='unique_comic_issue_person_role_credit'),
        ),
    ]
