# Generated by Django 6.0.6 on 2026-07-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicvolume',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
