# Generated by Django 6.0.6 on 2026-07-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_comicvolume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicissue',
            name='is_released',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
