# Generated by Django 6.0.6 on 2026-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_comicissue_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicrun',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('ended', 'Ended')], default='unknown', max_length=20),
        ),
    ]
