# Generated by Django 6.0.6 on 2026-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_comicrun_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicissue',
            options={'ordering': ['run', 'published_date', 'issue_number']},
        ),
        migrations.AlterModelOptions(
            name='comicvolumeissue',
            options={'ordering': ['volume', 'issue_order', 'issue__published_date', 'issue__issue_number']},
        ),
        migrations.RenameField(
            model_name='comicissue',
            old_name='store_date',
            new_name='published_date',
        ),
    ]
