# Generated by Django 6.0.6 on 2026-07-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_store_date_to_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicissue",
            name="official_detail_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comicissue",
            name="official_detail_missing_fields",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="comicissue",
            name="official_detail_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("complete", "Complete"),
                    ("incomplete", "Incomplete"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
            ),
        ),
    ]
