# Generated by Django 6.0.6 on 2026-07-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_comicissue_official_detail_checked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicOneShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_icon_url", models.URLField(blank=True, max_length=500)),
                ("image_medium_url", models.URLField(blank=True, max_length=500)),
                ("image_screen_url", models.URLField(blank=True, max_length=500)),
                ("image_screen_large_url", models.URLField(blank=True, max_length=500)),
                ("image_small_url", models.URLField(blank=True, max_length=500)),
                ("image_super_url", models.URLField(blank=True, max_length=500)),
                ("image_thumb_url", models.URLField(blank=True, max_length=500)),
                ("image_tiny_url", models.URLField(blank=True, max_length=500)),
                ("image_original_url", models.URLField(blank=True, max_length=500)),
                ("image_tags", models.CharField(blank=True, max_length=500)),
                ("display_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "display_image_source",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("source_data", "Source data"),
                            ("manual", "Manual"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("start_year", models.CharField(blank=True, max_length=20)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="one_shots",
                        to="catalog.comicpublisher",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "publisher__name",
                    "title",
                    "start_year",
                    "published_date",
                ],
            },
        ),
        migrations.CreateModel(
            name="ComicVolumeOneShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "one_shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collected_in",
                        to="catalog.comiconeshot",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_one_shots",
                        to="catalog.comicvolume",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "volume",
                    "item_order",
                    "one_shot__published_date",
                    "one_shot__title",
                ],
            },
        ),
        migrations.CreateModel(
            name="ComicVolumeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_issue_number", models.CharField(blank=True, max_length=50)),
                ("last_issue_number", models.CharField(blank=True, max_length=50)),
                ("issue_numbers_text", models.CharField(blank=True, max_length=500)),
                ("item_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collected_volume_links",
                        to="catalog.comicrun",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_runs",
                        to="catalog.comicvolume",
                    ),
                ),
            ],
            options={
                "ordering": ["volume", "item_order", "run__title", "run__start_year"],
            },
        ),
        migrations.AddConstraint(
            model_name="comiconeshot",
            constraint=models.UniqueConstraint(
                fields=("publisher", "title", "start_year"),
                name="unique_comic_one_shot_per_publisher_title_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="comicvolumeoneshot",
            constraint=models.UniqueConstraint(
                fields=("volume", "one_shot"), name="unique_comic_volume_one_shot"
            ),
        ),
        migrations.AddConstraint(
            model_name="comicvolumerun",
            constraint=models.UniqueConstraint(
                fields=("volume", "run"), name="unique_comic_volume_run"
            ),
        ),
    ]
