# Generated by Django 6.0.6 on 2026-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_comiconeshot_comicvolumeoneshot_comicvolumerun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicissue",
            name="marvel_issue_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="comicissue",
            name="marvel_issue_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="comiconeshot",
            name="marvel_issue_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="comiconeshot",
            name="marvel_issue_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="comicrun",
            name="marvel_series_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="comicrun",
            name="marvel_series_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="comicvolume",
            name="marvel_collection_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="comicvolume",
            name="marvel_collection_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
