# Generated by Django 6.0.6 on 2026-07-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_rename_marvel_sources_to_official_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicOneShotCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "one_shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.comiconeshot",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_shot_credits",
                        to="catalog.creditperson",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="one_shot_credits",
                        to="catalog.creditrole",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "one_shot",
                    "role__display_order",
                    "credit_order",
                    "person__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("one_shot", "person", "role"),
                        name="unique_comic_one_shot_person_role_credit",
                    )
                ],
            },
        ),
    ]
