# Generated by Django 6.0.6 on 2026-07-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_comiconeshotcredit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comicrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
