# Generated by Django 6.0.6 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_comicrun_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentReadingEraRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_reading_era_entries",
                        to="catalog.comicrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run",),
                        name="unique_current_reading_era_run",
                    )
                ],
            },
        ),
    ]
